version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1111
    ports:
      - 3306:3306

  app:
    image: app:latest
    depends_on:
      - docker-mysql